name: Github CI

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package manager
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Run pnpm install
        run: pnpm install --no-frozen-lockfile

      - name: Run pnpm build
        run: pnpm build

  lint-typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package manager
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Run pnpm install
        run: pnpm install --no-frozen-lockfile

      - name: Run pnpm lint
        run: pnpm lint:ci

      - name: Run pnpm typecheck
        run: pnpm tc
